### ISSUE TITLE
Temporary flash of new content

### ISSUE THREAD

**Issue by domchristie** [domchristie/turn#13]
When using non-view-transition animations alone, there's a temporary flash of the new content before enter. Current solution is to use v2.1.0 (where view transitions are disabled by default)

**Comment by domchristie** [comment]
> Current solution is to use v2.1.0 (where view transitions are disabled by default)

Or ensure that the target elements aren't visible during the view transition:

```css
.turn-view-transitions.turn-transition [data-turn-enter],
.turn-view-transitions.turn-before-transition [data-turn-enter] {
  opacity: 0;
}
```
